# Generated by Django 2.2 on 2020-04-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailPush',
        ),
    ]
